from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(305, 400)
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.centralwidget.setObjectName("centralwidget")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(0, 0, 300, 81))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(14)
        self.result_label.setFont(font)
        self.result_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.result_label.setAutoFillBackground(False)
        self.result_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 40, 40);")
        self.result_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.result_label.setObjectName("result_label")
        self.absolut_negative_btn = QtWidgets.QPushButton(self.centralwidget)
        self.absolut_negative_btn.setGeometry(QtCore.QRect(5, 350, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.absolut_negative_btn.setFont(font)
        self.absolut_negative_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.absolut_negative_btn.setObjectName("absolut_negative_btn")
        self.zero_btn = QtWidgets.QPushButton(self.centralwidget)
        self.zero_btn.setGeometry(QtCore.QRect(80, 350, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.zero_btn.setFont(font)
        self.zero_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.zero_btn.setObjectName("zero_btn")
        self.comma_btn = QtWidgets.QPushButton(self.centralwidget)
        self.comma_btn.setGeometry(QtCore.QRect(155, 350, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.comma_btn.setFont(font)
        self.comma_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.comma_btn.setObjectName("comma_btn")
        self.equals_btn = QtWidgets.QPushButton(self.centralwidget)
        self.equals_btn.setGeometry(QtCore.QRect(230, 350, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.equals_btn.setFont(font)
        self.equals_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.equals_btn.setObjectName("equals_btn")
        self.plus_btn = QtWidgets.QPushButton(self.centralwidget)
        self.plus_btn.setGeometry(QtCore.QRect(230, 300, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.plus_btn.setFont(font)
        self.plus_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.plus_btn.setObjectName("plus_btn")
        self.two_btn = QtWidgets.QPushButton(self.centralwidget)
        self.two_btn.setGeometry(QtCore.QRect(80, 300, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.two_btn.setFont(font)
        self.two_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.two_btn.setObjectName("two_btn")
        self.one_btn = QtWidgets.QPushButton(self.centralwidget)
        self.one_btn.setGeometry(QtCore.QRect(5, 300, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.one_btn.setFont(font)
        self.one_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.one_btn.setObjectName("one_btn")
        self.three_btn = QtWidgets.QPushButton(self.centralwidget)
        self.three_btn.setGeometry(QtCore.QRect(155, 300, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.three_btn.setFont(font)
        self.three_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.three_btn.setObjectName("three_btn")
        self.minus_btn = QtWidgets.QPushButton(self.centralwidget)
        self.minus_btn.setGeometry(QtCore.QRect(230, 250, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.minus_btn.setFont(font)
        self.minus_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.minus_btn.setObjectName("minus_btn")
        self.four_btn = QtWidgets.QPushButton(self.centralwidget)
        self.four_btn.setGeometry(QtCore.QRect(5, 250, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.four_btn.setFont(font)
        self.four_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.four_btn.setObjectName("four_btn")
        self.six_btn = QtWidgets.QPushButton(self.centralwidget)
        self.six_btn.setGeometry(QtCore.QRect(155, 250, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.six_btn.setFont(font)
        self.six_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.six_btn.setObjectName("six_btn")
        self.five_btn = QtWidgets.QPushButton(self.centralwidget)
        self.five_btn.setGeometry(QtCore.QRect(80, 250, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.five_btn.setFont(font)
        self.five_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.five_btn.setObjectName("five_btn")
        self.multy_btn = QtWidgets.QPushButton(self.centralwidget)
        self.multy_btn.setGeometry(QtCore.QRect(230, 200, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.multy_btn.setFont(font)
        self.multy_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.multy_btn.setObjectName("multy_btn")
        self.seven_btn = QtWidgets.QPushButton(self.centralwidget)
        self.seven_btn.setGeometry(QtCore.QRect(5, 200, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.seven_btn.setFont(font)
        self.seven_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.seven_btn.setObjectName("seven_btn")
        self.nine_btn = QtWidgets.QPushButton(self.centralwidget)
        self.nine_btn.setGeometry(QtCore.QRect(155, 200, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.nine_btn.setFont(font)
        self.nine_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.nine_btn.setObjectName("nine_btn")
        self.eight_btn = QtWidgets.QPushButton(self.centralwidget)
        self.eight_btn.setGeometry(QtCore.QRect(80, 200, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.eight_btn.setFont(font)
        self.eight_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.eight_btn.setObjectName("eight_btn")
        self.division_btn = QtWidgets.QPushButton(self.centralwidget)
        self.division_btn.setGeometry(QtCore.QRect(230, 150, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.division_btn.setFont(font)
        self.division_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.division_btn.setObjectName("division_btn")
        self.fraction_btn = QtWidgets.QPushButton(self.centralwidget)
        self.fraction_btn.setGeometry(QtCore.QRect(5, 150, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.fraction_btn.setFont(font)
        self.fraction_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.fraction_btn.setObjectName("fraction_btn")
        self.sqrt_btn = QtWidgets.QPushButton(self.centralwidget)
        self.sqrt_btn.setGeometry(QtCore.QRect(155, 150, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.sqrt_btn.setFont(font)
        self.sqrt_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.sqrt_btn.setObjectName("sqrt_btn")
        self.power_btn = QtWidgets.QPushButton(self.centralwidget)
        self.power_btn.setGeometry(QtCore.QRect(80, 150, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.power_btn.setFont(font)
        self.power_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.power_btn.setObjectName("power_btn")
        self.del_btn = QtWidgets.QPushButton(self.centralwidget)
        self.del_btn.setGeometry(QtCore.QRect(230, 100, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.del_btn.setFont(font)
        self.del_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.del_btn.setObjectName("del_btn")
        self.percent_btn = QtWidgets.QPushButton(self.centralwidget)
        self.percent_btn.setGeometry(QtCore.QRect(5, 100, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.percent_btn.setFont(font)
        self.percent_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.percent_btn.setObjectName("percent_btn")
        self.clea_all_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clea_all_btn.setGeometry(QtCore.QRect(155, 100, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.clea_all_btn.setFont(font)
        self.clea_all_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.clea_all_btn.setObjectName("clea_all_btn")
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setGeometry(QtCore.QRect(80, 100, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        self.clear_btn.setFont(font)
        self.clear_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 91, 91);")
        self.clear_btn.setObjectName("clear_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.result_label.setText(_translate("MainWindow", "0"))
        self.absolut_negative_btn.setText(_translate("MainWindow", "+/-"))
        self.zero_btn.setText(_translate("MainWindow", "0"))
        self.comma_btn.setText(_translate("MainWindow", "."))
        self.equals_btn.setText(_translate("MainWindow", "="))
        self.plus_btn.setText(_translate("MainWindow", "+"))
        self.two_btn.setText(_translate("MainWindow", "2"))
        self.one_btn.setText(_translate("MainWindow", "1"))
        self.three_btn.setText(_translate("MainWindow", "3"))
        self.minus_btn.setText(_translate("MainWindow", "-"))
        self.four_btn.setText(_translate("MainWindow", "4"))
        self.six_btn.setText(_translate("MainWindow", "6"))
        self.five_btn.setText(_translate("MainWindow", "5"))
        self.multy_btn.setText(_translate("MainWindow", "*"))
        self.seven_btn.setText(_translate("MainWindow", "7"))
        self.nine_btn.setText(_translate("MainWindow", "9"))
        self.eight_btn.setText(_translate("MainWindow", "8"))
        self.division_btn.setText(_translate("MainWindow", "/"))
        self.fraction_btn.setText(_translate("MainWindow", "1/x"))
        self.sqrt_btn.setText(_translate("MainWindow", "sqrt(x)"))
        self.power_btn.setText(_translate("MainWindow", "x^2"))
        self.del_btn.setText(_translate("MainWindow", "del"))
        self.percent_btn.setText(_translate("MainWindow", "%"))
        self.clea_all_btn.setText(_translate("MainWindow", "C"))
        self.clear_btn.setText(_translate("MainWindow", "CE"))
